### ISSUE TITLE
separate torus and closed grids

### ISSUE THREAD

**Issue by targos** [mljs/som#4]
the code will be simpler and easier to debug

**Comment by maasencioh** [comment]
@targos what is the state of this?

**Comment by targos** [comment]
@maasencioh answer to this question for all issues: the state is "pending". I do not have the time to maintain this project for now. It needs modernization and move to our current coding conventions. Anyone is welcome to help with that :)

**Comment by maasencioh** [comment]
@targos I can update the project if you want, but for some punctual issues like this one is complex without knowing what part of the code you are talking about
